import openai
import logging

from trialcurator.llm_client import LlmClient

logger = logging.getLogger(__name__)

class OpenaiClient(LlmClient):
    """
    A client for interacting with OpenAI's language models.

    This class wraps the OpenAI Python client and provides access to the
    OpenAI GPT models for generating text completions based on provided prompts.
    It extends the `LlmClient` abstract base class.
    """
    MODEL = "gpt-4o-2024-08-06"
    # gpt-4o-2024-08-06 is the default gpt-4o. See https://platform.openai.com/docs/models/gpt-4o

    # MODEL = "gpt-5-2025-08-07"  # Tested on 8 Aug 2025 & again on 8 Nov 2025. The outputs' quality is inferior. Sticking with gpt-4o for now.

    def __init__(self, temperature=0.0, top_p=1.0, model=MODEL):
        """
        Initialize the OpenaiClient class with specific model and tuning parameters.

        Parameters:
            temperature (float): Sampling temperature, controlling randomness in generated responses.
            top_p (float): Nucleus sampling value, controlling diversity in generated responses.
            model (str): The name of the OpenAI model to use (defaults to "gpt-4o").
        """
        self.wrapped_client = self._make_wrapped_client()
        self.temperature = temperature
        self.top_p = top_p
        self.model = model

    @staticmethod
    def _make_wrapped_client():
        client_factory = getattr(openai, "OpenAI", None) or getattr(openai, "Client", None)
        if client_factory is None:
            return None
        return client_factory()

    def llm_ask(self, user_prompt: str, system_prompt: str = None) -> str:
        """
        Send a prompt to the OpenAI language model and return the generated response.

        The method logs the prompt and the response at the DEBUG level for
        debugging (kept off INFO so batch runs do not flood the shared log).

        Parameters:
            system_prompt (str) (optional): The text prompt that sets the context/role the llm is to take on. E.g. An expert curator to interpret the rules or an assistant to simplify the language of the eligibility criteria
            user_prompt (str): The actual instructions to the llm. E.g. Extract the molecular criteria from this condition.

        Returns:
            str: The text response generated by the language model.
        """

        messages = []
        if system_prompt is not None:
            messages.append({"role": "system", "content": system_prompt})
            for line in system_prompt.splitlines():
                logger.debug(f'system prompt: {line}')

        messages.append({"role": "user", "content": user_prompt})
        for line in user_prompt.splitlines():
            logger.debug(f'prompt: {line}')

        completion = self._create_chat_completion(messages)

        # log the response
        response = self._completion_text(completion)
        for line in response.splitlines():
            logger.debug(f'response: {line}')

        return response

    def _create_chat_completion(self, messages):
        kwargs = {
            "model": self.model,
            "temperature": self.temperature,
            "top_p": self.top_p,
            "messages": messages,
        }

        if self.wrapped_client is not None:
            return self.wrapped_client.chat.completions.create(**kwargs)

        return openai.ChatCompletion.create(**kwargs)

    @staticmethod
    def _completion_text(completion):
        try:
            message = completion.choices[0].message
        except AttributeError:
            message = completion["choices"][0]["message"]

        if isinstance(message, dict):
            return message["content"]

        return message.content
