CREATE SCHEMA IF NOT EXISTS ctgov;
CREATE SCHEMA IF NOT EXISTS drug_identity;
CREATE SCHEMA IF NOT EXISTS drug_knowledge;
CREATE SCHEMA IF NOT EXISTS regulatory;
CREATE SCHEMA IF NOT EXISTS oncology_evidence;
CREATE SCHEMA IF NOT EXISTS scoring;
CREATE SCHEMA IF NOT EXISTS curation;